"""empty message

Revision ID: fd0d65e729ba
Revises: 070a482d8d5d
Create Date: 2018-11-25 18:37:16.638756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd0d65e729ba'
down_revision = '070a482d8d5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translation_jobs', sa.Column('timestamp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translation_jobs', 'timestamp')
    # ### end Alembic commands ###
